### ISSUE TITLE
技术雷达宣讲：enzyme 测试框架

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#101]
## Description

- What's Target？
  - 在五分钟之内讲明白 enzyme 是个什么东东，在技术雷达中的位置及其原因。
- What's Problem？
  - [x] 第一次面向办公室讲东西 => 大部分人都是熟人了，讲过的东西也挺多的。
  - [x] 时间太短，只有五分钟
  - [ ] 听众提问？
  - [ ] 收集反馈？
  - [ ] 自我介绍？

## TODOs

- [x] 整理思路 @XMind http://www.xmind.net/m/Cr4q
- [x] 看看别人怎么讲的 [enzyme react - YouTube](https://www.youtube.com/results?search_query=enzyme+react)
- [x] 完成 Slides @Keynote
- [x] 完成演讲内容 5W2H？

## References

- [enzyme react - 搜索结果 - 知乎](https://www.zhihu.com/search?type=content&q=enzyme+react)
- [enzyme react - Google Search](https://www.google.com/search?q=enzyme&oq=enzyme&aqs=chrome..69i57j69i65l3j0l2.1081j0j1&sourceid=chrome&ie=UTF-8#newwindow=1&q=enzyme+react)
- [react enzyme - Google Search 中文](https://www.google.com/search?hl=en&as_q=enzyme&lr=lang_zh-CN#lr=lang_zh-CN&newwindow=1&hl=en&tbs=lr:lang_1zh-CN&q=react+enzyme)
- [airbnb/enzyme: JavaScript Testing utilities for React](https://github.com/airbnb/enzyme)
- [Testing React Components with Enzyme - YouTube](https://www.youtube.com/playlist?list=PLikcwtJj8_mDxWUJhYChFarCPnAwio24e)
- [Introduction | Enzyme](http://airbnb.io/enzyme/index.html)

**Comment by JimmyLv** [comment]
试着用 Google Slides 来做 Presentation，又必然得去担心各种排版了，坑爹。

这哥们还有另外一个「探索」的功能，可以根据当前 Slide 的内容进行样式的自动优化，真是吸引你每新建一个页面就想去试试啊！这不坑爹么！我就想安安静静地做完我的 Slides 不行么，非得来个人工智能来帮倒忙啊？Slides 本来就是需要风格一致，你整个乱七八糟的每页都不一样是搞毛线！

我还是回去用的 nodeppt 吧，😂
