### ISSUE TITLE
围绕 Notion 建立全方位个人 Wiki 系统

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#102]
## Description

- What's Target？
  - 初衷只是想利用起 [jimmylv.github.io](https://github.com/JimmyLv/jimmylv.github.io) 个人主页的 [Wiki](https://github.com/JimmyLv/jimmylv.github.io/wiki) 页面，但是没想到这个 Wiki 竟然如此强大，结合 [gollum/gollum: A simple, Git-powered wiki with a sweet API and local frontend.](https://github.com/gollum/gollum) 就可以基于 Git 整理自己的知识体系结构。
- What's Problem？
  - 很久之前也尝试过但是最终没有坚持下来，不过那时只是浅尝辄止，而且没有内在的理由。
  - **Wiki 的方式来整理知识结构会不会与之前的 Diigo Outliner #99 计划有所冲突呢？**

## TODOs

- [x] 下载和使用  [gollum/gollum: A simple, Git-powered wiki with a sweet API and local frontend.]
  - [x] 寻求 gollum 替代品：gollum 界面太丑，且不知为何运行失败。 => 伪需求
  - [x] [TiddlyWiki — a non-linear personal web notebook](http://tiddlywiki.com/) 看起来非常不错。 => 但是跟 GitHub Wiki 不太吻合，增加了太多自己的东西。就我而言，还是在 Sublime 里面编辑就好啦，文件组织就依赖于文件系统也没问题。
  - [x] [claudioc/jingo: Node.js based Wiki](https://github.com/claudioc/jingo) 只用于在本地的展示，转念一想，既然我已经在 GitHub Wiki 上有了云端备份的展示界面，为何我还要在本地起一个 server？
  - [x] [scragg0x/realms-wiki: Git based wiki inspired by Gollum](https://github.com/scragg0x/realms-wiki) 很好看哇，基于 Python，本身承担了太多功能。
- [x] 作为本仓库的 submodules 用 Git 管理起来
- [x] Wiki 本身是有相互链接的语法的，跟带 host 的超链接有所不同。
  - [Adding images to wikis - User Documentation](https://help.github.com/articles/adding-images-to-wikis/)
  - [Adding links to wikis - User Documentation](https://help.github.com/articles/adding-links-to-wikis/)
- [x] GitHub wiki 基于 gollum 那最好的参考就应该是 [Home · gollum/gollum Wiki](https://github.com/gollum/gollum/wiki) => GitHub 好像并没有支持所有 gollum 的特性。
- [x] 借助 [doctoc](https://github.com/thlorenz/doctoc) 生成每个 page 的 TOC，以及手动添加各个pages 到 _Sidebar 里面。
- [ ] [Requarks/wiki: Wiki.js | A modern, lightweight and powerful wiki app built on NodeJS, Git and Markdown](https://github.com/Requarks/wiki)

## References

- [gollum:给wiki插上git的翅膀 - 简书](http://www.jianshu.com/p/9c35812b9bae)
- [基于Git的维基管理：gollum - 阳志平的网志](http://www.yangzhiping.com/tech/gollum.html)

**Comment by JimmyLv** [comment]
除了 Git 管理以外，根本就不如 Diigo 的 Outliner #99

**Comment by JimmyLv** [comment]
得益于 wiki 语法，以及借助工具生成 TOC，用来整理简单的知识结构也不错。

=> 不过又会好于 MindMap 嘛？

**Comment by JimmyLv** [comment]
人家 XMind 还可以直接嵌入到任何网页当中呢， 差不多就是最理想的形态。

![image](https://cloud.githubusercontent.com/assets/4997466/20649346/d38af728-b4f8-11e6-8132-2f72fa361dfc.png)

**Comment by JimmyLv** [comment]
Wiki 和 MindMap 并不冲突，重新思考这个话题。

之前只是**一直在强调形式，而不是内容**，没有形而上地去思考。

其实结合内容去思考形式，就会发现不同形式的内容有不同应用场景和价值。

- 大脑：记忆宫殿，反复升级，持续更新，加快阅读速度。（可能就是CPU调度中心，可作为零散碎片的集合，日记，日日记。思考能力，提炼升华，总结复述，融合扩充。）
- 资料库：Diigo 作为 Web 服务，直接作用于浏览网页时的标注和笔记，想法随时可以记录，距离最近，效率最高。（提高存入速度，WoW！）
- 个人笔记：Wiki/Outline 用于写入，结合 Markdown 非常好用；展示和记忆的时候用思维导图最棒（借助于 XMind 完全可以互通）；还可以放到 GitHub Wiki 作为公开展示；借助于 Dash 还可以用 Alfred 直接搜索。（存入时Diigo中的Outline可能可以作为中间产物；Wiki Markdown作为沉淀产物。读取时Dash+Alfred是最快速的，并且作为互联网搜索的公开产物，可展示化。）

------

- 日记：私人化，记录和倾诉；一些私密的个人信息（密码，照片 etc），直接放在备忘录里面就够啦，还可以加密！

然后再来谈谈辅助工具：

- Drafts 作为收集端真是棒！然后再借助于 Workflow 分发到其他地方。
- Letterspace 则可以用于iCloud同步和在iOS Spotlight 里面搜索；当然桌面端Sublime可以操作和搜索一切
- Evernote 作为混杂物，收集能力强，但是我可能不会再用咯，几种形式和内容都有了归宿。
- Instapaper 可能要被我放弃了，/(ㄒoㄒ)/~~ （不能被搜索，不能被及时阅读，可能唯一的作用就是作为Diigo之前的缓冲区，缓存器，暂缓期。）

Others/Maybe:

关键是Diigo Outline GUI不是特别好用，想借助工具自动化成Markdown，提高Markdown的【写入】速度；但其实也还好，复制粘贴也代表一种【思考】过程。而在**写Markdown文件是内存->硬盘的过程，写Outline的时候是CPU->内存的过程。**

Refs/Thanks: 

- https://diigo.com/0bl0y1 外部脑优化，【CPU-内存-硬盘】的比喻。
- https://diigo.com/0bl0y2 习得的知识技能转换率存在差异。

**Comment by JimmyLv** [comment]
- [ ] 修复图片不显示的问题，

ref: 

- https://stackoverflow.com/questions/41300176/how-can-i-show-a-image-on-the-main-github-wiki-page/41304291
- https://stackoverflow.com/questions/11915826/image-not-showing-up-in-readme-md-on-github
- https://github.com/gollum/gollum/wiki#linking-internal-images

**Comment by JimmyLv** [comment]
也许Notion才是最佳解决方案，
外部Web&内部DT

**Comment by JimmyLv** [comment]
已经确立下来，就是Notion啦：https://wiki.jimmylv.info/

**Comment by bigbugbean** [comment]
notion怎么嵌入xmind的思维导图

**Comment by JimmyLv** [comment]
@bigbugbean 需要使用 xmind.net 账号

![image](https://user-images.githubusercontent.com/4997466/88063891-276d4d00-cb9d-11ea-8091-88e099caa9b4.png)

**Comment by yntzes** [comment]
好活 mark一下
