### ISSUE TITLE
🐒 Retrospective | Marketplace Architecture Practice Evolution

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#106]
## Description

- What's Target？
  - complete [learning-microservices](https://github.com/JimmyLv/learning-microservices) book
  - summary multiple projects migration
  - from backend to frontend
- What's Problem？
  - lots of efforts
  - need lots of time (> 21 hours?)
  - one and half years go over
- What's consultant？
  - actually, this is my personal question
  - I need to be a consultant nex year
  - but how much experiences should I accumulate?

## TODOs

- [ ] complete [learning-mircoservice](https://github.com/JimmyLv/learning-mircoservice) book
- [ ] migarate notes inside DA
- [ ] build self real stencil project
- [ ] AtomicDesign
- [ ] AEM & React

## References

- 《REST 实战》
