### ISSUE TITLE
11/2016 Milestone Retrospection

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#107]
## 总结 Overview

[11/2016 Schedule Milestone](https://github.com/JimmyLv/jimmylv.github.io/projects#reports?report=burndown&milestoneId=2153602)

- 10 天完成了 25 points，如果（当初）是按照 hours 来估点的话，大概每天需要花费 2.5 hours。
- 需要进一步分析每个 issue 真正所花的时间，即 @Toggl 当中所记录过的时间。

## 统计

| Number & Description         | Estimation Points | Time Efforts |
| ---------------------------- | ----------------- | ------------ |
| #85 记录时间这件小事儿                | 3                 | 04:26:18     |
| #96 如何对时间进行分类？               | 8                 | 03:00:09     |
| #102 建立个人 Wiki 系统            | 2                 | 02:53:56     |
| #101 技术雷达宣讲：enzyme 测试框架      | 5                 | 06:11:19     |
| #90 Working time improvement | 1                 | 33:27 min    |
| #97 如何使用 XX 的标签系统？           | 1                 | 25:21 min    |

## 分析

- 还有大概 5 个点的 GitHub issues 没有被 Toggl 覆盖到，下回就严格按照这个流程走起！
- 跟敏捷流程当中一样，#Elaboration #Estimation #IPM #Sign-Off #Retro #Stand-Up 这些行为必不可少，但时间可能尽可能得减少。
- 不是说思考不重要，而是说更重要的应当在于执行！

[22 - 30 November](https://toggl.com/app/reports/summary/1327156/from/2016-11-22/to/2016-11-30/billable/both)，共 9 天，总记录时间 216:30:14，平均每天 24.05 hours。

![image](https://cloud.githubusercontent.com/assets/4997466/20863500/4863de44-ba07-11e6-9c29-49610b5213ee.png)

**睡眠**占去 71.5 hours，平均每天 7.95 hours，这里面没有包括懒床和睡前玩手机的时间。

- [ ] **Action 01**：去分析浪费的时间，减少 Stay in bed 的时间；
- [ ] **Action 02**： 增多 Afternoon Nap 的时间；

![](http://ww4.sinaimg.cn/large/006y8mN6jw1faejorb8ouj30zi0823yx.jpg)

**浪费**则共计 15 hours

- 其中 Just strolling 为 5 hours，Stay in bed 为 2.5 hours => 
  - [ ] **Action 03**：此处的记录不够详细，以后就把床上的时间专门列成 Stay in bed，不管你是赖床还是 Just strolling 玩手机去了，总之要减少！减少！减少！

- Foosball 时间为 3.3/(9-2)=0.45 hours 即平均每个工作日打了将近半个小时，还可以接受，😂
- 看电影什么的也算 okay，毕竟西部世界，不至于把时光浪费在烂片之上。

![](http://ww3.sinaimg.cn/large/006y8mN6jw1faejqv2vn4j30z00dqmy0.jpg)

**基本**，这是最令人忧伤的部分了，Eating 和 Commuting 确实会有所重叠，但是往往耗费时间的点其实都在用于通勤，但却又是无能为力的。一天的吃喝拉撒和路上的时间竟然占去了 (35-2)/9 = 3.7 个小时，感觉是一种不现实的幻觉，时间哪会怎么不够用？早中晚各一个小时，再加上洗洗衣服什么的，竟然也很有道理。

- [x] **Action 04**：继续记录时间，确认数据是否正常；

- [x] **Action 05**：与此同时尽可能跟别人一起次饭，还可以转化为有意义的交谈；

- [ ] **Action 06**：如果真是一个人的时候，试试听手机里的 Postcast 或者英文演讲。

![](http://ww2.sinaimg.cn/large/006y8mN6jw1faeje2ecpgj311e0i43zw.jpg)

**工作**方面则是一个被动的状态，太多的 Meetings 让人无法安心得 Programming

- 首先，Meeting 并不可怕，也是帮你理清思路，团队协作的一种有效方式。

- 无效 Meeting 当然也会有，于我而言也可以锻炼听力 or 口语；再不济，可以做一些比较轻松的事情，比如报销发票，😂

- Programming 的具体内容需要进一步分析，比如说最近 NMBL-674 这张卡估算为 5 points 而我花费了近 12 小时，那么以后我就能根据这个数据来估算我的完成效率和成本了。

- 工作需要「展现」价值，嗯。

  ![](http://ww1.sinaimg.cn/large/006y8mN6jw1faek58z6c4j30hc03uglw.jpg)

![](http://ww4.sinaimg.cn/large/006y8mN6jw1faek2k8wlfj30ze09o0ta.jpg)

在 5 个不同的 Target 里面，**工作**时间必然会是一个大部头，而 A1 里面的 Programming 会跟 A2 有很大重叠，毕竟工作时间也是玩技术，而与此同时，如何将其充分结合则是非常需要思考的话题。

- [ ] 比方说，**Action 07**：在工作中积极总结项目经验，#105 #106

- 而 A2 A3 其实都可以包含 Reading Watching Writing 等方式来进行提升，目前来说可以将其直接纳入
- 更重要的问题是：那么 A4 存在的价值在哪儿呢？「阅读 思考 写作」并不是一种目标而是手段，这一点值得思考；其实也是由于侧重点不一样吧，思考这部分更在于个人反思、总结，更像是非技术方面的 Retro，关注于持续改进。
- Projects 的分类比详细的 Description 更为重要，Description 的目标只是为了简化输入，但与此同时也会使得 TimeEntry 变得很多很混乱，从而导致分析时的困难。
  - [ ] **Action 08**：在分析时着重于大类而不是具体的 TimeEntry，分析时间的时间有待改进，需要减少。

![](http://ww4.sinaimg.cn/large/006y8mN6jw1faekelrc82j31kw0n0mzl.jpg)

> btw: 强烈安利 Typora 这款 Markdown 编辑器，实时渲染，特别适合这种需要插图的同时又需要分析图片的使用场景。

**Comment by JimmyLv** [comment]
![image](https://cloud.githubusercontent.com/assets/4997466/20839013/de3f7e14-b8e5-11e6-81ed-a9cd45e36d13.png)

![image](https://cloud.githubusercontent.com/assets/4997466/20839266/ded40678-b8e6-11e6-878c-0b87343cee9e.png)

![image](https://cloud.githubusercontent.com/assets/4997466/20839743/ac608a66-b8e8-11e6-9a17-ec4cfd0abf32.png)

**Comment by JimmyLv** [comment]
反思一下 GitHub 用于个人学习管理工具本身的一些问题：

1. 网速
2. 环节受限
  - 没有好的规划即 IPM 的时机不太好确定
  - 按照月份来划分 Iteration 似乎有点太长了
  - 在一个月里面的变化依然过多，欲望太多？
3. 记录本身也比较繁琐
  - 精简要做的事情
  - 看板只关注当前 Iteration

**Comment by JimmyLv** [comment]
下次 Retro 再来过一遍。
