### ISSUE TITLE
@TW_Academy Unit Test & Refactoring

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#119]
## Description

- What's Target？
  - 灌输“反馈”
  - 完美示例，打崩
  - => 给出解决方案
- What's Problem？
  - Time control

## TODOs

- [x] PPT/Slides => ref: [漫谈Web前端的『组件化』](http://leeluolee.github.io/fequan-netease/#/)
- [x] codebase: change mvn to gradle project
- [x] codebase: extract commands parser as Class
- [x] codebase: split to different branch
- [x] list, find or create the bad smells
- [x] setup self tools (Intellij with plugins, etc)

Finished slides: [@TW_Academy: Unit Test & Refactoring](https://jimmylv.github.io/tw-academy-slides/) 
用 Markdown 写 Slides，推荐 reveal.js 和 nodeppt…

## Feedbacks

- happy start…
- example -> self practise -> show & limit
- cover related knowledge
- exact definition

## References

- [Mocks Aren't Stubs](http://martinfowler.com/articles/mocksArentStubs.html)
- [TDD | 酷 壳 - CoolShell.cn](http://coolshell.cn/?s=TDD)
- [重构代码的7个阶段 | 酷 壳 - CoolShell.cn](http://coolshell.cn/articles/5201.html)
- [Mockito framework site](http://site.mockito.org/)
- [testing - What's the difference between a mock & stub? - Stack Overflow](http://stackoverflow.com/questions/3459287/whats-the-difference-between-a-mock-stub)
- [虚拟座谈会：TDD有多美？](http://www.infoq.com/cn/articles/virtual-panel-tdd)

**Comment by JimmyLv** [comment]
Finished slides: https://jimmylv.github.io/tw-academy-slides/

**Comment by JimmyLv** [comment]
- Slides [@TW_Academy: Unit Test & Refactoring](https://jimmylv.github.io/tw-academy-slides/#/)
- 思维导图 [UnitTest & Refactoring -- XMind Online Library](https://www.xmind.net/m/x7d5)
- 代码库 [JimmyLv/workshop.mars-rover-unittest-refactoring: A programming kata is an exercise which helps a programmer hone his skills through practice and repetition.](https://github.com/JimmyLv/workshop.mars-rover-unittest-refactoring)
