### ISSUE TITLE
12/2016 Milestone Retrospection

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#120]
## 总结

Estimation 的时候忽略了两个时间大怪兽：

- Annual Review · 13:11:12 
- Christmas Holiday(with LOVE) · 35:12:00 

[12/2016 Schedule Milestone](https://github.com/JimmyLv/jimmylv.github.io/issues#reports?report=burndown&milestoneId=2153603)：

- 完成 33/44 Points，根据估点平均每天需要花费 1.1 hours
- 完成 9/(13-1) Issues

![image](https://cloud.githubusercontent.com/assets/4997466/21646993/84bdcbc2-d2d3-11e6-9107-6c3f4241c2ed.png)

## 统计

| Number & Description         | Priority |Estimation Points | Time Efforts |
| ---------------------------- | -------- |----------------- | ------------ |
| #博客大赛# 《基于 GitHub 的敏捷学习方法之道与术》 #36 | Epic | 5 | 07:18:43
| 发掘生活需求 #51 | | Not estimated | 
| 文章自动化发布与数据统计脚本 #86 | 紧急: ★ 重要: ★★ | 5 | 05:09:53
| 如何玩转 StackOverflow？ #91 | 紧急: ★ 重要: ★ | 3 | Not recorded
| 《区块链将如何重新定义世界》 #109 | 紧急: ★ 重要: ★★ | 3 | 02:25:38
| #博客大赛# 使用 Enzyme 测试 React（Native）组件 #116 |  | 3 | 04:15:01
| @TW_Academy Unit Test & Refactoring #119 | 紧急: ★★★ 重要: ★★★ | 8 | 13:43:13
| 个人成长基础设施之硬件&软件篇 #121 | 紧急: ★ 重要: ★★ | 3 | 01:39:00
| 讨论学习的有效性 #125 | 紧急: ★ 重要: ★★★ | 3 | 02:03:39

## 分析

- 不知为何漏了一个 #91，（完美主义式）伤感…
- [ ] 对于 #51 这种没有 Estimation 的 Issue 就不再放到 Milestone 里面
- [ ] 对于 Epic 卡不再估点，不好 track…
- [ ] 放入 Milestone 都需要设置 Priority label

[01 - 31 December](https://toggl.com/app/reports/summary/1327156/from/2016-12-01/to/2016-12-31/billable/both)，共 31 天，总记录时间 741:20:38，平均每天 23.9 hours，记录较完美，继续坚持！:star:

![](http://7xjbdq.com1.z0.glb.clouddn.com/images/2016/1483540150734.png)

> 下次要避免 Without client  40:00 min   

### D.浪费    53:02:31

分析头三大时间杀手：

1. Just strolling  17:26:57    
2. Foosball    09:42:12    
3. Bad emotion 06:25:00    
4. Strolling with @Weibo   05:28:00    
5. Stay in bed 05:19:21

减少 strolling ！减少 strolling ！减少 strolling ！

- [ ] 详细记录 Strolling 的时候在干什么！
- [ ] 多看书！多看书！多看书！
- [ ] 不要 Bad emotion 导致刷微博！一天就没了！

### C.睡眠    244:41:29   

- Night Sleeping  240:38:10 · 平均 7.76 hours 每天
- Afternoon Nap   04:03:19 · 平均不到 8 mins，继续保持，中午要睡舒服

- [ ] Strolling 的时间要么 Reading 要么 直接睡觉！

### B.基本    127:41:47   

平均 4 个小时为了维持生活，不过也是为了更好的生活！

- Cleaning、Commuting、Eating 这是 Basic Life 最永恒的事件…
- 这里面还包括了买房、考驾校…… 这两个时间怪兽，在可预知的未来还会大量占用我的 Basic Life
- [ ] 尽量把 Commuting 的时间拿来听 XX 👂 ，事实上我也是正在这么做的…

### A5.休息 运动 感情 88:32:04    

只看前五：

1. Be with darling 35:12:00    
2. Just relaxing @AwayDay  15:08:00    
3. Talking with darling    13:33:15    
4. Game with Friends   06:50:54    
5. Gathering of friends    04:11:00

- 很高兴 Be & Talking with Darling 
- 跟朋友一起玩耍，也有意识得多聚了聚，nice
- @AwayDay 也算是一大时间怪兽，尽玩游戏去了，少了 Social
- 哈哈哈，总之 PS4 是在心里种草了…

### A4.阅读 思考 写作 36:10:25    

1. Fragment Reading    08:18:47    
2. #36 基于 GitHub 的敏捷学习方法总结 07:18:43    
3. Just talking    03:23:09

碎片阅读太多，但是没包括技术方面的 Fragment Reading 11:00:16，共计 19 hours
#109 和 #136 两本书的时间一共才花了 4 hours，当然没读完呗…

### A3.技能 学习 沟通 17:28:59    
 
1. @TW_Academy $Workshop   04:14:00    
2. 整理清单 @TickTick  03:30:10    
3. Self #Elaboration @GitHub   01:34:04

花在很多时间在 整理清单 和 GitHub 工具本身了… 但是相比之下还是花费较少的，如果把 Strolling 的时间用到这上面来进行 Reflection，当然会更好，GTD 也崇尚时常回顾，分阶段回顾。

### A2.技术 编程 产品 53:11:47    
    
1. #119 @TW_Academy Unit Test & Refactoring    13:43:13    
2. Fragment Reading    11:00:16    
3. #86 文章自动化发布与数据统计脚本  05:09:53

其实技术相关的东西倒是都会有专门的 issues 来追踪，也是 [基于 GitHub 的敏捷学习方法之道与术 - 吕立青的博客](https://blog.jimmylv.info/2016-12-04-agile-learning-based-on-github-issues/) 的主要关注点所在，用好 GitHub Issues 便是提高技术能力的好途径。

### A1.职业 工作 投资 119:51:34   

![](http://7xjbdq.com1.z0.glb.clouddn.com/images/2016/1483541697235.png)

平均每个工作日专注在工作本身事务上的时候有 5.7 个小时，自认为已经非常 contribution

- Working 66:18:27    
- Programming 29:19:30    
- Meeting 24:13:37

- [ ] 下次 #144 换这种按 Project 来 subgroup 进行分析：

![](http://7xjbdq.com1.z0.glb.clouddn.com/images/2016/1483541831379.png)

## Actions

回顾上一次 Retro #107 的 Action Items：

- [ ] **Action 01**：去分析浪费的时间，减少 Stay in bed 的时间； | 继续保持，争取比这次的要少 05:19:21
- [x] **Action 02**： 增多 Afternoon Nap 的时间；
- [x] **Action 03**：以后就把床上的时间专门列成 Stay in bed，不管你是赖床还是 Just strolling 玩手机去了，总之要减少！减少！减少！ | 可以看到的是 Stay in bed 的时间变多了，专门拿来记录
- [x] **Action 04**：继续记录时间，确认数据是否正常；
- [x] **Action 05**：与此同时尽可能跟别人一起次饭，还可以转化为有意义的交谈；
- [x] **Action 06**：如果真是一个人的时候，试试听手机里的 Postcast 或者英文演讲。
- [ ] **Action 07**：在工作中积极总结项目经验，#105 #106 | 简直伤感……
- [x] **Action 08**：在分析时着重于大类而不是具体的 TimeEntry，分析时间的时间有待改进，需要减少。

**Comment by JimmyLv** [comment]
一些截图

![image](https://cloud.githubusercontent.com/assets/4997466/21644411/4c71adac-d2c8-11e6-8ae2-8cbda689f284.png)

**Comment by JimmyLv** [comment]
搞定。
