### ISSUE TITLE
前端学习的网站推荐

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#131]
## Description

- What's Target？
  - collect awesome websites to learn front-end

## TODOs

- [ ] https://egghead.io/technologies/react
- [ ] https://frontendmasters.com/courses/
- [ ] https://online.reacttraining.com/courses
- [ ] http://wesbos.com/courses/
- [ ] https://thinkster.io/
- [ ] [LearnCode.academy - YouTube](https://www.youtube.com/channel/UCVTlvUkGslCV_h-nSAId8Sw)
- [ ] https://angular-university.io/
- [ ] https://www.fullstackreact.com/ & https://www.fullstackreact.com/30-days-of-react/
- [ ] https://www.youtube.com/c/reactcasts
- [ ] [ReactDOM - A weekly newsletter of the best ReactJS, React Native & GraphQL](https://reactdom.com/)
- [ ] [Ultimate Angular: Courses](https://ultimateangular.com/courses/)

## References

- [What developers channels do you follow on YouTube? - Hashnode](https://hashnode.com/post/what-developers-channels-do-you-follow-on-youtube-ciws3rznu00h5y353qhvm87oh)
- [Anyone knows any good resources to master React? - Hashnode](https://hashnode.com/post/anyone-knows-any-good-resources-to-master-react-cip2sc9aq02zwl953deex8q84#ciw245mw31a79qe53v6z6w5lt)

**Comment by JimmyLv** [comment]
## Escribe aquí tu respuesta usando Markdown

**Comment by JimmyLv** [comment]
资料堆积而已，如 Awesome 系列一样毫无意义。

原则：

- 付费买时间。
- follow 正确的人。
