### ISSUE TITLE
Pomotodo 原账号计划列表

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#26]
- [x] 理解前端框架中的常见设计模式 #编程 #思考总结 #236 
- [ ] ~~阅读 Vue 源码十日游，计时 #编程~~
- [x] Rethink 系列 结合实际 #实践 #思考总结
- [ ] ~~Ready for web future (by Angular2) #编程 #写作~~
- [ ] ~~MarsRover Pair TDD视频录制 #编程~~
- [x] MicroService最佳实践 #写作 #105 
- [x] 记录总结大型项目的技术 改进？ #软件 #思考 #22 
- [x] 阅读/翻译 python-guide #编程 #英语 #翻译 [[REFERENCE] · Issue #1 · JimmyLv/python-guide-zh](https://github.com/JimmyLv/python-guide-zh/issues/1)
- [x] 以gatling为例：在工作中如何即学即用？ #写作 [使用 Gatling 对服务器进行稳定性测试 · Learning-Microservices](https://jimmylv.gitbooks.io/learning-microservices/content/best-practice/Stability_and_Performance_Testing_using_Gatling.html)
- [x] 程序员必备的基本技能与习惯 #写作 #88 
- [x] 目前我的写作系统 #写作 [敏捷写作：macOS 环境下写作系统的最优配置 | 吕立青的博客](https://blog.jimmylv.info/2016-06-11-write-in-mac-os-x/)
- [x] 敏捷方法指导个人成长 #写作 #36 
- [ ] ~~Angular 2, Anfular 1.x, React横向对比 #写作 #编程~~
- [ ] ~~Angular-Meteor开源项目阅码 #编程 #写作~~
- [x] 如何在TDD实践中实现设计模式 #写作 #239 
- [x] 非科班程序员的自卑与自傲 #写作 #思考总结 #238
- [x] Java 8 新特性阅读与实践 #主题阅读 [[REFERENCE] · Issue #1 · JimmyLv/better-java-zh](https://github.com/JimmyLv/better-java-zh/issues/1)
- [ ] ~~Angular 1.5，展望 Angular 2.0 #Session~~
- [x] Angular Meteor 实时聊天室 #Session => https://github.com/JimmyLv/vue-firebase-demo
- [x] 向「前」看，2016 骚窝计划 #思考 #152 #84 
- [x] Pragmatism：服务于商业的技术 #编程 #写作 [微信小程序 (1)：技术是如何服务于商业的？ | 吕立青的博客](https://blog.jimmylv.info/2017-01-10-wechat-app-with-business-and-technology-01/)
- [x] web前端开发模式演变输出文章 #写作 [Web 前端开发模式演变 | 吕立青的博客](https://blog.jimmylv.info/2015-11-02-history-about-web-development-evolution/)
- [x] 聊聊 Webpack 中的 require #思考 #前端 [前端模块化小史，Webpack 入门 | 吕立青的博客](https://blog.jimmylv.info/2016-03-28-js-moudle-history-and-webpack-in-action/)

**Comment by JimmyLv** [comment]
每一项都由于计划变动 close 或是新建了新的 Issue
