### ISSUE TITLE
2016 末期关注点，精简目标与最终冲刺

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#84]
## Tech

1. Front-End
  - [x] ☑︎React + Redux => 比较完美的方案 [Ant.Design](https://ant.design) & [dva](https://github.com/dvajs/dva) #16 
  - [x] ☒微博粉服开发 => Money (built by dva & ant.design) => 直接改用 ReactNative 好了… #146 
  - [x] ◇全栈工程师 => 纳米学位 via [Udacity](https://classroom.udacity.com/nanodegrees/nd004/parts/0041345400/modules/004134540075460/lessons/3497159389/concepts/35283794830923) => #104
  - [x] ☒AEM => 开发者证书 #112 （短期内是不行了，😂）
  - [x] ☑︎小程序 => 撸一个掘金 clone 出来 #83 => 搞一个系列的 Workshop #89 
  - [x] ☒梦想集市 => 公司内部开源排名、业余/黑工项目 => 放弃吧
2. Others
  - [x] ◇区块链 => 看完两本书 #110 #109 **把 D.浪费 Just strolling 06:07:28 改成看书难道不好吗？一周就看完了！** => 看完了一本，不错，继续加油
  - [x] ◇~~深度学习 => 跟完 WorkShop~~ => 只去过一次，放弃。 => 继续先建个 issue #147  Track 一下

## Capacity

- [x] ☑︎博客大赛 => ☑︎两篇总结性文章《基于 GitHub 的敏捷学习方法》#36 & ☒《元博客：教你如何写博客的一篇博客》 #99 => 只完成了计划中的一篇，但额外输出了一篇 Enzyme 的文章 #116 
- [x] ☑︎思沃讲堂 => Unit Testing & Refactoring #119 
- [x] ◇项目总结 => MircoService & AtomDesign || 虚拟项目 3 back-end + 2 front-end #106 => 持续进行 ing
- [x] ☒视频直播 => 从思沃起航？=> 意义不大，还有更重要的事情。
- [x] ◇英语 => 音标强化练习 @多说英语 => 与此同时有更多英语材料，比如 #104 视频中的单词都记到 @有道词典 里面去，定期复习。 => 竟然在公司里面有了专门的培训，还在 billable 时间， #148

**Comment by linesh-simplicity** [comment]
妈蛋，还有50天不到了，你的 todolist 还有13个…那个，放松就好。。

**Comment by JimmyLv** [comment]
所有完成的，未完成的，都有了自己的归宿，这个 Issue 就可 close 了。

完成 ☑︎ 4
进行中 ◇ 5 
未完成 ☒ 4
