### ISSUE TITLE
记录时间这件小事儿 

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#85]
## TODOs

- [x] [工具挑选](https://github.com/JimmyLv/jimmylv.github.io/issues/85#issuecomment-261977938)
- 记录中
  - [x] 如何分类 #96 
  - [x] 简化输入 => 全英文 https://github.com/JimmyLv/jimmylv.github.io/issues/96#issuecomment-263099272
  - [x] 记录停止时复盘 #97 
- 记录后
  - [x] 每日分析 @GridDiary
  - [x] 每周分析 @Toggl [Weekly report](https://toggl.com/app/reports/weekly/1327156/period/prevWeek/billable/both)
  - [ ] 每月分析 2016.11.30

## References

😁 🍉 [The 20 Best Time-Tracking Apps](https://zapier.com/blog/best-time-tracking-apps/)

> ## Don’t Spend All Your Free Time Learning Link
> It’s easy to feel that you’re so far behind you need to be coding and learning every minute. This is a one-way ticket to burnout-ville. Set some time aside to develop your skillset, see if you can negotiate some time with your boss so it’s scheduled in and spend the rest of the time doing what you love.
> I’ve had some of my coding epiphanies at the gym. Exercising is extremely important for your mind as well as your body. Try and do at least 20–30 minutes a day to keep your mind sharp and help prevent burnout.
> Make time for your family and friends — try not to talk shop with them!

via [Not An Imposter: Fighting Front-End Fatigue – Smashing Magazine](https://www.smashingmagazine.com/2016/11/not-an-imposter-fighting-front-end-fatigue/?_branch_match_id=320201438266250921#dont-spend-all-your-free-time-learning)

**Comment by JimmyLv** [comment]
> 依然纠结于 Toggl、Pomotodo、时间块和潮汐之间...

还是回到需求，从需求出发来让我重新认识自己：

1. 记录时间的几大境界：
    - 记录本身，感受时间的流逝
    - 回顾记录，进行总结分析
    - 预估时间，更精确的计划与执行
2. 进一步研究 GTD 流程，阅读《GetThingsDone》：
    - 收集（滴答清单）
    - 整理（滴答清单 + GitHub issues，并且预估 🍅 个数）
    - 执行（在滴答清单/GitHub issues 里面直接开启 Toggl 开始计时）
    - 回顾（Toggl 报告分析、总结、计划）

> 30分钟是番茄时间法的标准时长，以它为单位来记录，可以让自己有意识地在一段时间内把一件事保持专注地做完，而不在中途被其它事情打断，这样才有更高的效率。

- [时间块](http://timeblocks-simple-daily-activi.appstor.io/zh/) => **弃用**
    + 已经用了这么久的时间块，也该来说说对它的感受了。
    + 首先是优点，记录非常得简单、快捷，用户评论最省时间的时间记录工具没有之一。
    + 30 分钟的时间块原本让我感觉是个优点，会让人有意识地去利用整块时间，但是却发现很容易掉入整点陷阱，已经开始了浪费，那不如整个 30 分钟都记为浪费，等到下一个时间块再开始干活儿？
    + 然后来说说缺点，只有 iOS 客户端，本着轻松记录的缘由，从而依然需要打开手机来用，最理想的状态其实是彻底隔绝手机才对。
    + 还有就是它的 Reports 实在没法进行分析，而已不得不说有点儿混乱的说，并且没办法在其他平台上查看。
    + 其实这也跟「做分析的时机」有关，你想想如果要做回顾总结的时间点，显然是在电脑端更为方便得统计，与此同时就需要更加详细的记录细节和报告分析。
    + 一款应用的强大之处往往就在于简约而不简单，可以说时间块只做到了前者而忽略了后者，随着记录的深入就必然会有更进一步的需求出现，而时间块相关功能中的「关联内容」算是一个常识，但依然不能满足进一步的需求。我想说的一个典范其实就是「滴答清单」，真正的简约而不简单，扩展性超强。
- [Toggl](https://toggl.com/app/timer) => **得宠**
    + 最完善的时间记录工具，这就是我为什么要纠结于要不要用它的原因。
    + 全端支持，Web、Desktop、iOS 都有，而其他软件往往只有手机上才有，但其实我大部分时间都还是在用电脑啊不是么？
    + 已经内置了 Pomodoro Timer（电脑端）
    + 还可以主动提醒该记录时间啦，防止忘记开始和结束
    + iOS 上的简约反而是一件好事，让你可以不用关于现在的 Reports，说实话在手机端作分析真不是一件适当的事情。（「在正确的时间做正确的事情」）
    + iOS 没有支持 Pomodoro 也是一件好事儿，避免长时间看手机难道不是么？在手机上做番茄本身就不是一件美好的事情，如果还出现用手机的 App 做番茄记录而实际却工作在电脑端，结束了还得重新点亮手机再开始一遍，岂不是有点儿 fun？
    + 更加重要的是电脑端的操作实在太友好了，简直友好到哭 😭，因为装了 Chrome 插件之后就可以在网页项目 Start timer 的小图标，点击之后就可以直接把当前标题作为记录项，也就是说连任何输入都不需要了呀，什么 GitHub、滴答清单（需要手动添加 permission）、Jira 通通都支持！！
- [Pomotodo](https://pomotodo.com/app/) => **弃用**
    + 这玩意儿说实话真心就没有太大必要了，于我而言。
    + 番茄本身不能用来做记录，现在我对它的定义就只在于执行时刻的专注和休息提醒。
    + 一旦你开始了用番茄个数来作为时间记录，就很有可能掉入一个「追求数量」的陷阱，毕竟越多的番茄代表着越高的效率，那是不是上厕所/洗澡也想来个番茄呢？稍微轻松愉快而不需要那么高注意力的时候也想开个番茄来充充数呢？
    + 番茄工作法是很好的，可以无视任何拖延理由就「立即执行」，当然更重要的就是休息提醒，以保持更长久的专注力。但是千万不要本末倒置用来「考验」自己的专注力，人性亦然。
- [潮汐](https://itunes.apple.com/cn/app/chao-xi-bao-chi-zhuan-zhu/id1077776989?mt=8) => **得宠**
    + 新加入「时间小助手」豪华午餐，小而美又单纯的典范。
    + 白噪音 + 番茄，但是番茄时长可以设为 120 分钟，就单纯作为白噪声软件来使，记得开启屏幕常亮模式不然会被系统休眠的，😂。
    + 统计功能不在于个数，而在于时长！统计功能不在于个数，而在于时长！统计功能不在于个数，而在于时长！
    + 可以有「沉浸模式」，即开启白噪声之后就不能离开潮汐 App 否则就失败了，😭

**Comment by JimmyLv** [comment]
![image](https://cloud.githubusercontent.com/assets/4997466/20489562/0051f426-b046-11e6-8304-96bc35b75143.png)

**Comment by JimmyLv** [comment]
另外不得不说「勿扰模式」是一个伟大的发明：

![image](https://cloud.githubusercontent.com/assets/4997466/20489699/76ffadde-b046-11e6-955d-9a2f1dca4a6c.png)

**Comment by JimmyLv** [comment]
经过近两周试用的一点儿感想：

- 常做的一些事情都已经固定下来了，从而使得输入成本降低。
- 随着标签的增多 #97，打 Tags 复盘的动力反而降低了。
- 回顾报告还需要进一步的改善和优化，重要的是看到进步，比如说浪费比例降低，目标指数提高 etc
- 当然咯，还得输出一篇文章才行，#103

**Comment by xiangjianmeng** [comment]
#!new issue
