### ISSUE TITLE
文章自动化发布与数据统计脚本

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#86]
## TODO

- [x] jianshu http://www.jianshu.com/writer
- [ ] zhihu
- [x] juejin https://gold.xitu.io/editor/md
- [x] segmentfault https://segmentfault.com/write
- [x] v2ex https://www.v2ex.com/new
- [x] oschina https://my.oschina.net/JimmyLv/blog/edit 23min
- [x] csdn http://write.blog.csdn.net/mdeditor 40min
- [ ] div.io http://div.io/new-topic
- [ ] toutiao http://toutiao.io/contribute
- [ ] gank http://gank.io/submit
- [ ] 前端乱炖 http://www.html-js.com/
- [ ] https://www.w3ctech.com/
- [ ] http://www.qdfuns.com/
- [ ] Gitbook.com
- [ ] Gitbook.cn
- [ ] http://www.jobbole.com/
- [ ] http://www.51cto.com/
- [ ] http://www.doit.com.cn/
- [ ] https://www.cnblogs.com/
- [ ] http://www.infoq.com/cn/

English platform:

- [ ] [Hashnode](https://hashnode.com/)
- [ ] medium
- [ ] Hacker News
- [ ] Quora

freelancer platform:

- coding
- 程序员客栈

## References

- https://github.com/airbob/personal/blob/master/scripts/post2blog/ReadMe.md
- [網路爬蟲 - Nightwatch + Cheerio = 神鵰俠侶 | Andy's Blog](http://bbandydd.github.io/blog/2016/10/20/nightwatch-cheerio/)
- [x] 还可以有纯浏览器版的实现，ref: http://www.moye.me/2016/11/19/nightmare/
- [segmentio/nightmare: A high-level browser automation library.](https://github.com/segmentio/nightmare)
  - https://github.com/segmentio/nightmare#selectselector-option

**Comment by JimmyLv** [comment]
Finished jianshu version.

**Comment by JimmyLv** [comment]
@linesh-simplicity @Yaowenjie Any other tech platforms are worth supporting?

**Comment by linesh-simplicity** [comment]
23333，你丫用 what 不好非要用英格里斯！let me check

**Comment by linesh-simplicity** [comment]
* [ ] medium
* [ ] toutiao
* [ ] gank

**Comment by Yaowenjie** [comment]
If you want to share something in English:
- [ ] Medium
- [ ] Hacker News

Other small platforms, which I never used, hahaha:
- [ ] [diycode](http://www.diycode.cc/)
- [ ] [React Native Tools
](http://www.rntools.co/)

匿

**Comment by JimmyLv** [comment]
@linesh-simplicity You can implement it by using API, rather than UI testing scripts.

**Comment by JimmyLv** [comment]
@Yaowenjie There is a wonderful English platform called https://hashnode.com/ which has beautiful UI and excellent contents.

**Comment by Yaowenjie** [comment]
@JimmyLv Marked.

**Comment by JimmyLv** [comment]
5 hours 已到…  但其实剩下的工作都是重复工作，体力活。

**Comment by linesh-simplicity** [comment]
这么多平台！

**Comment by JimmyLv** [comment]
竟然，[karllhughes/side-project-marketing: A checklist of tactics for marketing your side projects.](https://github.com/karllhughes/side-project-marketing)

**Comment by xiang578** [comment]
能否询问一下，你是如何自动在简书上发文的

**Comment by JimmyLv** [comment]
@xiang578 用的 nighmare.js 模拟用户点击和输入哈、
