### ISSUE TITLE
学习微信小程序 & 准备 Session/Workshop

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/jimmylv.github.io#89]
## TODOs

> refs: 参考以往经验 #101 #119

- [x] 思维导图 => 被 Diigo 的 Outliner 替代
- [x] Slides => Generated from scripts by nodeppt
- [x] 演示项目 demo => show on phone https://minapp.com
- [x] 实战项目 demo：https://github.com/ThoughtWorksInc/wxapp-workshop

## 正文

> 什么？！听说最近「微信小程序」已经火遍了大半个中国，前端人员又要来改变世界了？不管是程序猿还是产品经理，或者是 HR 们都已经对这个话题无比~~饥渴~~兴奋了；不得不感叹一下现在这世道，每天不学习真是顿感要被后浪拍死在沙滩上了，不管如何，在我司这快速学习的能力是必备的，得益于不辣么紧张不用加班的项目氛围，现在就是学习「微信小程序」的最佳时机；不等 1.9 号小程序正式发布，我们现在就来借助工具，快速了解这玩意儿到底是个什么东西！

这前言也忒长了点吧，让我们来复盘「我要学习微信小程序」这个 Idea 诞生的时机、场景吧：

- 朋友圈一篇《内测邀请函》的文章开始被广泛流传
- 张小龙所发朋友圈截图被广泛流传
- 各大技术微信群开始转发，讨论
- 知乎开始讨论：[如何评价 9 月 21 日开始内测的「微信小程序」？ - 知乎](https://www.zhihu.com/question/50874500)
- 各大公众号开始跟进，发表“独家”观点
- 各大科技/技术网站开始独家发布 xx

总之，作为吃光群众的我们开始叽叽呱呱，一方面是因为没有内测名额必然是玩不了的，一方面是感叹前端的世界真是奇妙又令人精疲力尽。但是终究，这玩意儿的价值不可忽略，又一种新的 Hybrid App 方案诞生在微信的「操作系统」梦想之上。

终于，等到了[如何看待2016年11月3日微信小程序公测？ - 知乎](https://www.zhihu.com/question/52262542)这个问题的诞生，也就意味着我们普通开发者终于有机会一睹小程序的风采，亲身上阵与「微信小程序」来一场期待已久的翻云覆雨。

--------

搞完之后总结一发「如何快速输出一场 Session or/and Workshop？#135 」

Well: 

- ask for help, work as a coaching team
- record and replay video, to improve continuously
- whole team self retro after the workshop
- prepare teaching scripts and generate slides
- collect feedback from students (而且用上了「腾讯投票」小程序…)
- @Diigo, to learn and organize knowledge
- @TickTick, to record and execute actions

Less Well: 

- not help other enough
- too much to learn
- tons of overtime than estimation
- too much catch-up meeting with teammates

**Keep Actions:**

- [ ] works as a team
- [ ] make good use of tools (Diigo & TickTick)
- [ ] reduce catch-up meeting times & time
- [ ] clear and definite audiences
- [ ] split different cards to record process (Toogl)

![](http://7xjbdq.com1.z0.glb.clouddn.com/images/2016/1485179799389.png)

所以真正花在 Workshop 上的时间应该是 Catch-Up、Rehearsal、Retro 这几项，共计 **10 hours**
然后在现场 Presentation 和 Coaching 的时间是有 **7 hours**
当然，学习的时间占去了 **15 hours**

关于小程序就还剩下任务

- [ ] #155 黑工项目
- [ ] #156 写一篇技术文章

**Comment by JimmyLv** [comment]
微信小程序专题，持续进行 ing

现已完成公司内部的系列 Workshop
